// 📊 データ領域：ステージ4（20問のプールから毎回10問がランダムに選ばれます）
window.quizStage4 = [
    { question: "A: What do you want to eat for dinner? \nB: ________", choices: ["Curry and rice, please.", "I want to watch TV."], correct: "Curry and rice, please.", translation: "A: よるご飯に何が食べたい？ B: カレーライスをおねがいします。", hint: "🪄 相手は「eat（食べる）」についてきいているよ。おいしい食べものはどっちかな？", explanation: "<b>eat</b>（食べる）ときかれているから、食べものの <b>Curry and rice</b>（カレーライス）で答（こた）えるのが大正解（だいせいかい）！" },
    { question: "A: Which do you like better, cats or dogs? \nB: ________", choices: ["I like cats better.", "Yes, I do."], correct: "I like cats better.", translation: "A: ネコとイヌ、どっちのほうがすき？ B: ネコのほうがすきだよ。", hint: "🪄 「どっちのほうがすき？」ときかれているよ。すきな動物（どうぶつ）を教えてあげてね。", explanation: "<b>Which do you like better 〜?</b>（どっちのほうがすき？）には、自分のすきな方を <b>I like cats better.</b> のように答えるよ！" },
    { question: "A: Whose cute dog is this? \nB: It's ________.", choices: ["Ken's", "Ken"], correct: "Ken's", translation: "A: これはだれの可愛いイヌ？ B: ケンくんの（もの）だよ。", hint: "🪄 「だれの？」ときかれているから、「〜くんのものだよ」という言葉をえらぼう。", explanation: "「〜のもの」と言（い）いたいときは、お名前に「 <b>'s</b> 」をつけて <b>Ken's</b>（ケンくんの）の形（かたち）にするまほうをつかうよ。" },
    { question: "A: How do you go to school? \nB: By ________.", choices: ["bus", "eight o'clock"], correct: "bus", translation: "A: どうやって学校にいくの？ B: バスでいくよ。", hint: "🪄 「どうやって（いく方法）」をきかれているよ。乗りものの名前をえらんでね。", explanation: "いく方法をきく <b>How 〜?</b> には、<b>By bus</b>（バスで）のように乗りものの名前をつかって答えるのが正解！" },
    { question: "A: What is your sister doing now? \nB: She is ________ a book.", choices: ["reading", "reads"], correct: "reading", translation: "A: お姉ちゃんはいま何をしてるの？ B: 本を読んでいるところだよ。", hint: "🪄 「いま〜しているところ」のときは、言葉のうしろに何がくっつくかな？", explanation: "<b>is</b> のうしろに <b>〜ing</b> をくっつけると、「いま〜しているところだよ」という現在進行形（げんざいしんこうけい）のまほうになるんだ！" },
    { question: "A: Does your father play tennis? \nB: No, he ________.", choices: ["doesn't", "don't"], correct: "doesn't", translation: "A: お父さんはテニスをする？ B: うううん、しないよ。", hint: "🪄 質問が「Does」からはじまっているよ。お返事もおしりを合わせてね。", explanation: "お父さん（He）のことについて <b>Does 〜?</b> できかれているから、お返事も <b>he doesn't</b>（しないよ）をつかうのが正解だよ。" },
    { question: "A: What color is your new bicycle? \nB: It's ________.", choices: ["pink", "small"], correct: "pink", translation: "A: 新しい自転車は何色？ B: ピンク色だよ。", hint: "🪄 相手は「color（いろ）」をきいているよ。大すきな「いろ」の名前をえらぼう！", explanation: "何色かをきかれているから、色の名前の <b>pink</b> が正解！smallは「ちいさい」という意味（いみ）だよ。" },
    { question: "A: Where did you go yesterday? \nB: I ________ to the park.", choices: ["went", "go"], correct: "went", translation: "A: きのうはどこにいったの？ B: 公園にいったよ。", hint: "🪄 「yesterday（きのう）」のお話だから、過去（かこ）のまほうをえらんでね。", explanation: "「きのう」のことについて話すときは過去形（かこけい）にするよ。<b>go</b>（いく）の過去のまほうは <b>went</b>（いった）になるんだ！" },
    { question: "A: Can I have some water, please? \nB: ________", choices: ["Here you are.", "Thank you."], correct: "Here you are.", translation: "A: お水をすこしいただけますか？ B: はい、どうぞ。", hint: "🪄 「お水をちょうだい」と言われたよ。「はい、どうぞ！」と優しく渡してあげよう。", explanation: "モノを「はい、どうぞ！」と差し出す（さしだす）ときは <b>Here you are.</b> の呪文（じゅもん）をつかうよ。" },
    { question: "A: When do you play video games? \nB: ________ dinner.", choices: ["After", "Under"], correct: "After", translation: "A: いつテレビゲームをするの？ B: ご飯のあとにやるよ。", hint: "🪄 ゲームをするタイミングだよ。ご飯の「あと」かな？それともご飯の「した」？", explanation: "「〜のあとで」というときは <b>After</b>（アフター）のまほうをつかうよ。Underだと「ご飯の下」になっちゃうよ。" },
    // 💡 ここから新しく追加された10問（合計20問のプール）
    { question: "A: Why are you so happy? \nB: ________ it's my birthday today!", choices: ["Because", "But"], correct: "Because", translation: "A: どうしてそんなに嬉しそうなの？ B: だって、今日はわたしの誕生日なんだもん！", hint: "🪄 「Why（どうして？）」ときかれたら、理由（りゆう）を答えるときの言葉からはじめよう。", explanation: "「どうして？」という質問（しつもん）に「なぜなら〜だからだよ」と答えるときは <b>Because</b> のまほうをつかうよ！" },
    { question: "A: Look! It's snowing! \nB: Wow! Let's ________ a snowman!", choices: ["make", "making"], correct: "make", translation: "A: 見て！雪が降ってるよ！ B: わあ！雪だるまを作ろうよ！", hint: "🪄 「Let's 〜（〜しよう）」のうしろにくる言葉は、変身（へんしん）しない元の形のままだよ。", explanation: "Let's のうしろにつなげる動きの言葉（動詞）は、ingなどをつけない元の形（原形）にするルールなんだ。だから <b>make</b> が正解！" },
    { question: "A: I am very tired today. \nB: You should ________ to bed early.", choices: ["go", "went"], correct: "go", translation: "A: 今日はとっても疲れちゃった。 B: 早く寝たほうがいいよ。", hint: "🪄 「〜したほうがいいよ（should）」のうしろも、変身しない元の形の言葉がくるよ。", explanation: "<b>should</b>（〜したほうがいい）のうしろにくる言葉も、過去形（went）ではなく元の形の <b>go</b> をつかうのが正解だよ。" },
    { question: "A: Do you know that girl? \nB: Yes. I know ________ very well.", choices: ["her", "she"], correct: "her", translation: "A: あの女の子を知ってる？ B: うん。彼女のことをよく知っているよ。", hint: "🪄 動（うご）きの言葉のうしろで「彼女を（に）」を表（あらわ）す言葉に変身させてね。", explanation: "「〜を知っている」のうしろで「彼女を」と言いたいときは、<b>she</b> ではなく <b>her</b> の形（かたち）に変わるひっかけのまほうだよ！" },
    { question: "A: Can you speak English? \nB: Yes, a ________.", choices: ["little", "small"], correct: "little", translation: "A: 英語はお話しできる？ B: うん、すこしだけね。", hint: "🪄 「すこしだけ話せるよ」というときの、お決まりの魔法のフレーズだよ。", explanation: "言葉や言葉づかいが「すこしだけ」と言いたいときは <b>a little</b> をつかうよ。small は物の「大きさ」が小さいときにつかうんだ。" },
    { question: "A: What are you going to do this weekend? \nB: I'm going to ________ my grandmother.", choices: ["visit", "visiting"], correct: "visit", translation: "A: 今週末は何をする予定なの？ B: おばあちゃんの家に行く予定だよ。", hint: "🪄 「be going to 〜（〜する予定だ）」の「to」のうしろにくる言葉の形だよ。", explanation: "〜する予定（よてい）を表す <b>to</b> の後ろにくる言葉も、ingなどをつけない元の形にするよ。だから <b>visit</b>（たずねる）が正解！" },
    { question: "A: It's hot today. \nB: Yes. Please open the window. \nA: ________.", choices: ["All right", "Thank you"], correct: "All right", translation: "A: 今日はあついね。 B: そうだね。窓を開けてくれる？ A: いいよ。", hint: "🪄 窓（まど）をあけて、と頼（たの）まれて「いいよ！わかったよ」とお返事してね。", explanation: "おねがいを優しく引き受けるときは <b>All right.</b>（いいですよ・わかりました）のまほうをかえそう！" },
    { question: "A: How ________ is your brother? \nB: He is twelve years old.", choices: ["old", "tall"], correct: "old", translation: "A: お兄ちゃん（弟）は何歳なの？ B: 12歳だよ。", hint: "🪄 答えで「years old（〜さい）」と言っているから、年齢（ねんれい）をきくフレーズだね。", explanation: "何歳（なんさい）かをきくときは <b>How old 〜?</b> をつかうよ！How tall は「背（せ）の高さ」をきくときにつかうんだ。" },
    { question: "A: I have two ________. \nB: Wow, they are very big!", choices: ["boxes", "box"], correct: "boxes", translation: "A: 箱を2つ持っているんだ。 B: わあ、とても大きいね！", hint: "🪄 「two（2つの）」だから、箱（box）がたくさんのときの形（複数形）に変身させてね。", explanation: "2つ以上のときは言葉のうしろに s や es をつけるよ。box は <b>boxes</b> に変身する、たくさんのまほうだよ！" },
    { question: "A: I usually get up ________ six thirty. \nB: That's early!", choices: ["at", "on"], correct: "at", translation: "A: わたしはいつも6時半に起きるよ。 B: 早いね！", hint: "🪄 「6時半（じかん）」のまえにくっつける、お決まりの短い言葉だよ。", explanation: "「〇時〇分」というカチッとした時間のまえには <b>at</b> をくっつけるルールだよ。on は「月曜日」などの曜日（ようび）につかうんだ。" }
];

