// 📊 データ領域：ステージ2（20問のプールから毎回10問がランダムに選ばれます）
window.quizStage2 = [
    { question: "A: What is that? \nB: It's ________ apple.", choices: ["an", "a"], correct: "an", translation: "A: あれは何？ B: リンゴだよ。", hint: "🪄 リンゴ（apple）のあたまの音にちゅうもくしてね！", explanation: "つぎの言葉が「あ・い・う・え・お」の音からはじまるときは、<b>a</b> が <b>an</b> に変身（へんしん）するよ！" },
    { question: "A: Who is that boy? \nB: ________ is my brother.", choices: ["He", "She"], correct: "He", translation: "A: あの男の子はだれ？ B: 私のお兄ちゃん（弟）だよ。", hint: "🪄 「boy（男（おとこ）の子）」のことをお話ししているよ。", explanation: "男の人のことは <b>He</b>（かれは）、女の人のことは <b>She</b>（かのじょは）という魔法をつかうよ。" },
    { question: "A: Whose umbrella is this? \nB: It's ________.", choices: ["mine", "my"], correct: "mine", translation: "A: これはだれの傘？ B: わたしの（もの）だよ。", hint: "🪄 「わたしのもの」と言い切る魔法の呪文をえらぼう。", explanation: "「わたしの！」と言いたいときは <b>mine</b>（わたしのもの）をつかうよ。my は後ろに言葉が必要なんだ。" },
    { question: "A: What time is it? \nB: It's ________ o'clock.", choices: ["three", "thirteen"], correct: "three", translation: "A: いま何時？ B: 3時だよ。", hint: "🪄 時計（とけい）の数字だよ。13時は英語の時計にはないかも…？", explanation: "時間の <b>o'clock</b> につけられるのは1から12までの数字だよ。thirteen（13）はひっかけだよ。" },
    { question: "A: Where is my cat? \nB: It's ________ the table.", choices: ["under", "in"], correct: "under", translation: "A: わたしのネコはどこ？ B: テーブルの下にいるよ。", hint: "🪄 ネコちゃんが隠れそうな場所は、テーブルの「なか」？それとも「した」？", explanation: "テーブルの「した」は <b>under</b> をつかうよ。in は箱（はこ）の中などにつかうよ。" },
    { question: "A: Let's play tennis. \nB: Yes, ________.", choices: ["let's", "I do"], correct: "let's", translation: "A: テニスをしようよ！ B: うん、そうしよう！", hint: "🪄 「Let's 〜」と誘（さそ）われたよ。あいての言葉に合わせてね。", explanation: "<b>Let's 〜</b>（〜しよう！）と誘われたら、<b>Yes, let's.</b> とかえすのがなかよしの合言葉！" },
    { question: "A: Do you have ________ pens? \nB: Yes, I have two.", choices: ["any", "some"], correct: "any", translation: "A: ペンを（いくつか）持ってる？ B: うん、2本持ってるよ。", hint: "🪄 質問（しつもん）する文（？のつく文）のときに変身する言葉だよ。", explanation: "ふつうの文では some だれど、質問する文（疑問文）になると <b>any</b> に化（ば）けるひっかけのまほうだよ！" },
    { question: "A: Are you a student? \nB: Yes, ________.", choices: ["I am", "you are"], correct: "I am", translation: "A: あなたは生徒さんですか？ B: はい、そうです。", hint: "🪄 「あなたは？」ときかれているから、だれのことについて答えるのかな？", explanation: "「あなたは？」ときかれたら、「はい、<b>わたしは</b>そうです」と答えるから <b>Yes, I am.</b> になるよ。" },
    { question: "A: How ________ is this notebook? \nB: It's two dollars.", choices: ["much", "many"], correct: "much", translation: "A: このノートはいくらですか？ B: 2ドルだよ。", hint: "🪄 お値段（ねだん）をきくときの、きまった魔法のフレーズだよ。", explanation: "値段（お金）をきくときは <b>How much 〜?</b> をつかうよ。many は数（かず）をかぞえるときにつかうよ。" },
    { question: "A: Look ________ that big bird! \nB: Wow!", choices: ["at", "on"], correct: "at", translation: "A: あの大きな鳥を見て！ B: わあ！", hint: "🪄 「〜をみて！」というときの、2つの文字のセットだよ。", explanation: "「〜をみる」は <b>look at</b> というセットのまほうだよ！on は「〜の上に」になっちゃうよ。" },
    // 💡 ここから新しく追加された10問
    { question: "A: What is that? \nB: It's ________ orange.", choices: ["an", "a"], correct: "an", translation: "A: あれは何？ B: オレンジだよ。", hint: "🪄 オレンジ（orange）のあたまの音（お）にちゅうもくしてね！", explanation: "「お」からはじまる言葉の前だから、a ではなく <b>an</b> が大正解だよ！" },
    { question: "A: Who is that girl? \nB: ________ is my sister.", choices: ["She", "He"], correct: "She", translation: "A: あの女の子はだれ？ B: 私の姉（妹）だよ。", hint: "🪄 「girl（女（おんな）の子）」のことをお話ししているよ。", explanation: "女の人のことをさして「かのじょは〜」というときは <b>She</b> のまほうをつかうよ。" },
    { question: "A: Is this book yours? \nB: Yes, it's ________.", choices: ["mine", "me"], correct: "mine", translation: "A: この本はあなたの？ B: うん、わたしの（もの）だよ。", hint: "🪄 「わたしのものだよ！」と言い切る言葉をえらぼう。", explanation: "「わたしのもの」を表（あらわ）す <b>mine</b> が正解！me にすると「それは わたし です」になっちゃうよ。" },
    { question: "A: Where is my ball? \nB: It's ________ the box.", choices: ["in", "on"], correct: "in", translation: "A: わたしのボールはどこ？ B: 箱（はこ）の中にあるよ。", hint: "🪄 ボールが箱の「なか」にあるのか「うえ」にあるのか、どっちが自然（しぜん）かな？", explanation: "箱の中にすっぽり入っているときは <b>in</b> をつかうよ。on は箱の上（表面）にのっているときだよ。" },
    { question: "A: What ________ do you like? \nB: I like green.", choices: ["color", "food"], correct: "color", translation: "A: 何色が好き？ B: みどり色が好きだよ。 ", hint: "🪄 答（こた）えで「green（みどり色）」と言っているね。", explanation: "みどり色は「いろ」だから、何の色かをきく <b>color</b> が大正解！foodは「食べもの」だよ。" },
    { question: "A: Do you have a dog? \nB: No, I ________.", choices: ["don't", "am not"], correct: "don't", translation: "A: イヌは飼ってる？ B: うううん、飼ってないよ。", hint: "🪄 「Do you 〜?」できかれているよ。否定（ひてい）の「〜ないよ」の言葉をえらんでね。", explanation: "Do できかれたら、答えるときも Do のなかまをつかうよ。ちがうときは <b>don't</b> になるんだ！" },
    { question: "A: How ________ books do you have? \nB: I have five books.", choices: ["many", "much"], correct: "many", translation: "A: 本を何冊持ってるの？ B: 5冊持っているよ。", hint: "🪄 本の「数（かず）」をきいているよ。数えられるものをきくときの言葉は？", explanation: "本の冊数（数）をきくときは <b>How many 〜?</b> をつかうよ。much は値段（お金）をきくときだよ。" },
    { question: "A: Are you a teacher? \nB: No, ________.", choices: ["I'm not", "you aren't"], correct: "I'm not", translation: "A: あなたは先生ですか？ B: いいえ、ちがいます。", hint: "🪄 「あなたは？」ときかれているから、自分のことを答えてね。", explanation: "「あなたは？」への返事だから「いいえ、<b>わたしは</b>ちがいます」となる <b>I'm not</b> が正解！" },
    { question: "A: Let's go home. \nB: No, ________.", choices: ["let's not", "I don't"], correct: "let's not", translation: "A: おうちに帰ろうよ。 B: うーん、やめておこう。", hint: "🪄 「Let's 〜（〜しよう）」を「やめとこう」と断（ことわ）る、すこし難しいひっかけのまほうだよ。", explanation: "Let's 〜 のお誘いを断るときは、後ろに not をつけて <b>let's not</b>（やめておこう）とするのが正解！" },
    { question: "A: Listen ________ the music. \nB: OK.", choices: ["to", "at"], correct: "to", translation: "A: 音楽（おんがく）をきいてね。 B: はーい。", hint: "🪄 「〜をきく」というときの、きまった2つの文字のセットだよ。", explanation: "「〜をきく」は <b>listen to</b> というセットのまほうだよ！look at（〜をみる）とまちがえやすいから気をつけてね！" }
];

