// 📊 データ領域：ステージ3（20問のプールから毎回10問がランダムに選ばれます）
window.quizStage3 = [
    { question: "A: What is your favorite sport? \nB: ________", choices: ["I like soccer.", "I like yellow."], correct: "I like soccer.", translation: "A: 一番すきなスポーツは何？ B: サッカーがすきだよ。", hint: "🪄 相手（あいて）は「スポーツ」についてきいているよ。", explanation: "<b>sport</b>（スポーツ）をきかれているから、<b>soccer</b>（サッカー）と答（こた）えるのが大正解！" },
    { question: "A: Happy birthday, Lily! This is for you. \nB: ________", choices: ["Thank you!", "You're welcome."], correct: "Thank you!", translation: "A: リリー、お誕生日おめでとう！これ、どうぞ。 B: ありがとう！", hint: "🪄 お誕生日プレゼントをもらったよ！うれしい気持ちを言葉にしよう。", explanation: "プレゼントを「どうぞ」と渡（わた）されたら、<b>Thank you!</b>（ありがとう！）の魔法（まほう）をえらぼう。" },
    { question: "A: May I use your eraser? \nB: ________", choices: ["Sure. Here you are.", "No, I can't."], correct: "Sure. Here you are.", translation: "A: 消しゴムをかりてもいい？ B: いいよ、はいどうぞ。", hint: "🪄 「かりてもいい？」ときかれて、「いいよ！」と貸（か）してあげる言葉だよ。", explanation: "「いいよ、どうぞ！」と貸してあげるときは <b>Sure. Here you are.</b> の呪文（じゅもん）がぴったり。" },
    { question: "A: Welcome to our house! \nB: ________", choices: ["Thank you.", "Nice to meet you."], correct: "Thank you.", translation: "A: 私のおうちへようこそ！ B: ありがとう。", hint: "🪄 お友達のおうちに招待されて、「ようこそ！」と迎えられたよ。", explanation: "<b>Welcome to 〜</b>（〜へようこそ！）と歓迎（かんげい）されたら、うれしい気持ちをこめて <b>Thank you.</b> と返（かえ）そう！" },
    { question: "A: Which juice do you want, orange or apple? \nB: ________", choices: ["Orange, please.", "Yes, please."], correct: "Orange, please.", translation: "A: オレンジとリンゴ、どっちのジュースがいい？ B: オレンジをおねがいします。", hint: "🪄 「どっちがいい？」ときかれているから、すきな方をえらんでね。", explanation: "選ぶ質問のときは、<b>Yes / No</b> ではなく、ほしい方の名前を <b>Orange, please.</b> のように答えるよ。" },
    { question: "A: When is your birthday? \nB: It's ________.", choices: ["in October", "on Monday"], correct: "in October", translation: "A: お誕生日はいつ？ B: 10月だよ。", hint: "🪄 「いつ？」ときかれているよ。お誕生日の「月（つき）」を教えてあげよう！", explanation: "お誕生日をきかれたら、何月かを教えてあげよう。<b>October</b>（10月）がついている方が正解！" },
    { question: "A: Wash your hands before dinner. \nB: ________", choices: ["OK, Mom.", "You too."], correct: "OK, Mom.", translation: "A: ご飯の前に手を洗いなさいね。 B: わかったよ、お母さん。", hint: "🪄 お母さんに「手を洗ってね」と言われたよ。「はーい！」とお返事しよう。", explanation: "お母さんの言うことに「わかったよ！」と答えるときは <b>OK, Mom.</b> がバッチリ！" },
    { question: "A: Goodbye, Daddy! Have a nice day! \nB: ________", choices: ["Thank you. See you.", "Good night."], correct: "Thank you. See you.", translation: "A: バイバイお父さん！いってらっしゃい！ B: ありがとう、またね。", hint: "🪄 お仕事にいくお父さんに「いってらっしゃい！」と言ったあとのやりとりだよ。", explanation: "「いってらっしゃい」と言われたお父さんは、<b>Thank you. See you.</b>（ありがとう、またね！）とお出かけしていくよ。" },
    { question: "A: Shall we play computer games? \nB: ________", choices: ["That's a good idea.", "I am ten."], correct: "That's a good idea.", translation: "A: パソコンのゲームをいっしょにやらない？ B: それはいいね！", hint: "🪄 「いっしょに遊ぼう！」というお誘いに、「いいね！そうしよう！」と賛成（さんせい）しているよ。", explanation: "お誘いに「いいね！」と答えるときは <b>That's a good idea.</b> というステキなまほうの言葉をつかうよ。" },
    { question: "A: It's rain today. I can't go to the park. \nB: ________", choices: ["That's too bad.", "Me too."], correct: "That's too bad.", translation: "A: 今日は雨だ。公園にいけないや。 B: それは残念だね。", hint: "🪄 お友達が「公園にいけなくて悲しい」と言っているよ。やさしく声をかけてあげよう。", explanation: "お友達が残念なことを言っているときは、<b>That's too bad.</b>（それは残念だね）となぐさめてあげよう！" },
    // 💡 ここから新しく追加された10問
    { question: "A: What are you looking for? \nB: My ________. I want to write a letter.", choices: ["notebook", "shoes"], correct: "notebook", translation: "A: 何を探しているの？ B: ノートだよ。手紙を書きたくて。 ", hint: "🪄 後ろの文で「手紙（てがみ）を書きたい」と言っているよ。使うものはどっち？", explanation: "手紙を書くために探しているものだから、<b>notebook</b>（ノート）が正解。shoesは靴（くつ）だから書けないね。" },
    { question: "A: Where are you going, Tom? \nB: To the ________. I want to read some books.", choices: ["library", "pool"], correct: "library", translation: "A: トム、どこに行くの？ B: 図書館だよ。本を読みたくて。", hint: "🪄 「本（ほん）をよみたい」と言っているね。本がたくさんある場所はどこかな？", explanation: "本を読む場所だから <b>library</b>（図書（としょ）館）が大正解！pool（プール）だと本が濡（ぬ）れちゃうよ。" },
    { question: "A: Can I watch TV now, Dad? \nB: No. Do your ________ first.", choices: ["homework", "breakfast"], correct: "homework", translation: "A: お父さん、いまテレビ見てもいい？ B: だめだよ。先に宿題をやりなさい。", hint: "🪄 テレビを見る前に「先にやりなさい！」と怒（おこ）られちゃう定番（ていばん）のものといえば？", explanation: "「先にやりなさい！」と言われるものだから <b>homework</b>（宿（しゅく）題）が正解。breakfast（朝ご飯）は「やる」とは言わないよ。" },
    { question: "A: Excuse me. Where is the restroom? \nB: ________. Follow me.", choices: ["Over there", "Thank you"], correct: "Over there", translation: "A: すみません、お手洗いはどこですか？ B: あそこですよ。ついてきてください。", hint: "🪄 場所（ばしょ）をきかれたから、「あっちだよ」と教えてあげよう！", explanation: "場所を指（さ）して「あそこですよ」と教えるときは <b>Over there</b> のまほうをつかうよ。" },
    { question: "A: I have a cold today. \nB: Oh, ________.", choices: ["Take care.", "You're welcome."], correct: "Take care.", translation: "A: 今日はかぜをひいちゃったんだ。 B: あら、お大事にね。", hint: "🪄 お友達（ともだち）が風邪（かぜ）をひいちゃったみたい。優しい言葉をかけてね。", explanation: "体調（たいちょう）がわるい相手を気づかって「お大事にね」というときは <b>Take care.</b> のまほうをかけるよ。" },
    { question: "A: Hello. May I speak to Mary, please? \nB: ________. Hold on, please.", choices: ["Sure", "Goodbye"], correct: "Sure", translation: "A: もしもし。メアリーさんをお願いします。 B: いいですよ。ちょっと待ってね。", hint: "🪄 お電話（でんわ）のやりとりだよ。「いいよ、待っててね」とお返事してね。", explanation: "電話で「いいですよ！」と引き受けるときは <b>Sure</b> がぴったり。Hold on は「そのまま待ってね」という意味だよ。" },
    { question: "A: What subjects do you like? \nB: I like ________.", choices: ["math and science", "guitars and pianos"], correct: "math and science", translation: "A: 何の教科がすきですか？ B: 算数と理科がすきだよ。", hint: "🪄 「subjects（きょうか・お勉強）」についてきかれているよ。学校のお勉強はどっち？", explanation: "教科（きょうか）をきかれているから、<b>math and science</b>（算数と理科）が正解。もう一方は楽器（がっき）だね。" },
    { question: "A: Do you want another cup of tea? \nB: No, ________. I'm full.", choices: ["thank you", "please"], correct: "thank you", translation: "A: お茶をもう一杯いかがですか？ B: いいえ、結構です。おなかいっぱいです。", hint: "🪄 「No」のうしろにつけて、「もう十分（じゅうぶん）だよ、ありがとう」と優しくことわる魔法だよ。", explanation: "お腹いっぱいで断るときは、<b>No, thank you.</b>（いいえ、結構です）と丁寧（ていねい）に言うのがまほうのルールだよ。" },
    { question: "A: How was the movie yesterday? \nB: It was ________!", choices: ["wonderful", "next week"], correct: "wonderful", translation: "A: きのうの映画はどうだった？ B: すばらしかったよ！", hint: "🪄 映画（えいが）の感想（かんそう）を教えてあげてね。", explanation: "映画がどうだったか（感想）をきかれているから、<b>wonderful</b>（すばらしい）が正解。next weekは「来週」という意味だよ。" },
    { question: "A: See you tomorrow, Jack! \nB: ________", choices: ["Bye!", "Good morning!"], correct: "Bye!", translation: "A: ジャック、また明日ね！ B: バイバイ！", hint: "🪄 「また明日ね！」とバイバイのあいさつをされたよ。元気に返そう！", explanation: "わかれるときのあいさつだから、<b>Bye!</b>（バイバイ！）とかえすのが大正解だよ！" }
];
